// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ncwW2Qgif2pGwQDF81hXqa
// Component: ABnpG58oqYch

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Logo from "../../Logo"; // plasmic-import: vUtPh7iXuorR/component
import GameBalance from "../../GameBalance"; // plasmic-import: gwn5sYqUZdjz/component
import ProfileEntrance from "../../ProfileEntrance"; // plasmic-import: kD3fRv5nUYyl/component

import { useScreenVariants as useScreenVariants_2BvNreuf1Eto } from "./PlasmicGlobalVariant__DesktopBase"; // plasmic-import: 2BVNreuf1ETO/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ncwW2Qgif2pGwQDF81hXqa/projectcss
import sty from "./PlasmicTopNavBar.module.css"; // plasmic-import: ABnpG58oqYch/css

createPlasmicElementProxy;

export type PlasmicTopNavBar__VariantMembers = {};
export type PlasmicTopNavBar__VariantsArgs = {};
type VariantPropType = keyof PlasmicTopNavBar__VariantsArgs;
export const PlasmicTopNavBar__VariantProps = new Array<VariantPropType>();

export type PlasmicTopNavBar__ArgsType = {};
type ArgPropType = keyof PlasmicTopNavBar__ArgsType;
export const PlasmicTopNavBar__ArgProps = new Array<ArgPropType>();

export type PlasmicTopNavBar__OverridesType = {
  navBar?: Flex__<"div">;
  navBackground?: Flex__<"div">;
  logo?: Flex__<typeof Logo>;
  gameBakance?: Flex__<typeof GameBalance>;
};

export interface DefaultTopNavBarProps {
  className?: string;
}

const $$ = {};

function PlasmicTopNavBar__RenderFunc(props: {
  variants: PlasmicTopNavBar__VariantsArgs;
  args: PlasmicTopNavBar__ArgsType;
  overrides: PlasmicTopNavBar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $translator = usePlasmicTranslator?.();

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    desktopBase: useScreenVariants_2BvNreuf1Eto()
  });

  return (
    <div
      data-plasmic-name={"navBar"}
      data-plasmic-override={overrides.navBar}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.navBar
      )}
    >
      <div
        data-plasmic-name={"navBackground"}
        data-plasmic-override={overrides.navBackground}
        className={classNames(projectcss.all, sty.navBackground)}
      >
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__nKuIx)}
        >
          <Logo
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            className={classNames("__wab_instance", sty.logo)}
          />

          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___5VL1H)}
          >
            <GameBalance
              data-plasmic-name={"gameBakance"}
              data-plasmic-override={overrides.gameBakance}
              className={classNames("__wab_instance", sty.gameBakance)}
            />

            <ProfileEntrance
              className={classNames(
                "__wab_instance",
                sty.profileEntrance__i9Qzs
              )}
            />

            <ProfileEntrance
              className={classNames(
                "__wab_instance",
                sty.profileEntrance__v29M
              )}
            />
          </Stack__>
        </Stack__>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navBar: ["navBar", "navBackground", "logo", "gameBakance"],
  navBackground: ["navBackground", "logo", "gameBakance"],
  logo: ["logo"],
  gameBakance: ["gameBakance"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navBar: "div";
  navBackground: "div";
  logo: typeof Logo;
  gameBakance: typeof GameBalance;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTopNavBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTopNavBar__VariantsArgs;
    args?: PlasmicTopNavBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTopNavBar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTopNavBar__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTopNavBar__ArgProps,
          internalVariantPropNames: PlasmicTopNavBar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTopNavBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navBar") {
    func.displayName = "PlasmicTopNavBar";
  } else {
    func.displayName = `PlasmicTopNavBar.${nodeName}`;
  }
  return func;
}

export const PlasmicTopNavBar = Object.assign(
  // Top-level PlasmicTopNavBar renders the root element
  makeNodeComponent("navBar"),
  {
    // Helper components rendering sub-elements
    navBackground: makeNodeComponent("navBackground"),
    logo: makeNodeComponent("logo"),
    gameBakance: makeNodeComponent("gameBakance"),

    // Metadata about props expected for PlasmicTopNavBar
    internalVariantProps: PlasmicTopNavBar__VariantProps,
    internalArgProps: PlasmicTopNavBar__ArgProps
  }
);

export default PlasmicTopNavBar;
/* prettier-ignore-end */
