// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTopUp2ndStepModal,
  DefaultTopUp2ndStepModalProps
} from "./plasmic/free_fire_simulator/PlasmicTopUp2ndStepModal";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TopUp2ndStepModalProps extends Omit<DefaultTopUp2ndStepModalProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTopUp2ndStepModalProps altogether and have
// total control over the props for your component.
export interface TopUp2ndStepModalProps extends DefaultTopUp2ndStepModalProps {}

function TopUp2ndStepModal_(
  props: TopUp2ndStepModalProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicTopUp2ndStepModal to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTopUp2ndStepModal are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TopUp2ndStepModalProps here, but feel free
  // to do whatever works for you.

  return <PlasmicTopUp2ndStepModal profileModal={{ ref }} {...props} />;
}

const TopUp2ndStepModal = React.forwardRef(TopUp2ndStepModal_);
export default TopUp2ndStepModal;
