// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicTopUp1stStepModal,
  DefaultTopUp1stStepModalProps
} from "./plasmic/free_fire_simulator/PlasmicTopUp1stStepModal";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface TopUp1stStepModalProps extends Omit<DefaultTopUp1stStepModalProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultTopUp1stStepModalProps altogether and have
// total control over the props for your component.
export interface TopUp1stStepModalProps extends DefaultTopUp1stStepModalProps {}

function TopUp1stStepModal_(
  props: TopUp1stStepModalProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicTopUp1stStepModal to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicTopUp1stStepModal are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all TopUp1stStepModalProps here, but feel free
  // to do whatever works for you.

  return <PlasmicTopUp1stStepModal profileModal={{ ref }} {...props} />;
}

const TopUp1stStepModal = React.forwardRef(TopUp1stStepModal_);
export default TopUp1stStepModal;
